version: '3'
services:
  dev:
    image: mla2:Jupiter_python
    build:
     context: .
     dockerfile: python.dockerfile
    ports:
      - 9001:8080
    volumes:
      - ./source_code:/root/code
      - ./.vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=80
  mlflow:
     image: mla2:mlflow
     platform: linux/x86_64
     build: 
      context: .
      dockerfile: mlflow.dockerfile
     volumes:
      - ./_mlflow:/mlflow
     ports:  
      - 5000:5000  